title: untitled
description: >- # ここに説明文
  いかがわしいゲームを作っています

url: "https://danayagi.github.io" # 自分のURLに変えてください
baseurl: "" # ルートドメインなら空文字でOK

theme: minima

timezone: Asia/Tokyo
plugins:
  - jekyll-seo-tag